### ISSUE TITLE
Not working with iOS 14.1 swiftUI 2.0

### ISSUE THREAD

**Issue by ghost** [programmingwithswift/SwiftUINumbersOnlyTextField#1]
It's not working if we type characters first, after type digit it will remove the character.

**Comment by programmingwithswift** [comment]
Thanks @GaurangVyas13, I will take a look at this.

**Comment by programmingwithswift** [comment]
@GaurangVyas13, I have just tested this, while iOS 14, and 14.1 have this issue, 14.2 and 14.4 don't. I don't have the time at the moment to try and figure out why this is happening, it seems like a bug or something. I will update the article to reflect this finding. Thanks for bringing it up! If you happen to figure out a solution, feel free to create a PR.

**Comment by lijh8** [comment]
no problem for me on iOS 14.6 and Xcode 12.5
